# Generated by Django 4.2.4 on 2025-08-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='recipe_ingredients',
        ),
    ]
